### ISSUE TITLE
WritableSettingsStore wrapper

### ISSUE THREAD

**Issue by reduckted** [VsixCommunity/Community.VisualStudio.Toolkit#104]
Although it's not _too_ difficult to use, creating a `WritableSettingsStore` is a bit cumbersome, and certainly not easy to discover. Here's my proposed API for a wrapper class. It borrows some techniques from the `CommandBase` class.

First, an attribute that defines the "collection path" to use.

```cs
[AttributeUsage(AttributeTargets.Class)]
public sealed class SettingsCollectionAttribute : Attribute {
    public SettingsCollectionAttribute(string collectionPath);
}
```

And then the wrapper base class:

```cs
public abstract class UserSettings<T> where T : class, new()
{
    public async static Task<T> GetAsync();

    protected bool GetBoolean(bool defaultValue = false, [CallerMemberName] string? propertyName = null);
    protected void SetBoolean(bool value, [CallerMemberName] string? propertyName = null);

    protected int GetInt32(int defaultValue = 0, [CallerMemberName] string? propertyName = null);
    protected void SetInt32(int value, [CallerMemberName] string? propertyName = null);

    protected long GetInt64(long defaultValue = 0, [CallerMemberName] string? propertyName = null);
    protected void SetInt64(long value, [CallerMemberName] string? propertyName = null);

    protected string GetString(string defaultValue = "", [CallerMemberName] string? propertyName = null);
    protected void SetString(string value, [CallerMemberName] string? propertyName = null);

    protected void ClearValue([CallerMemberName] string? propertyName = null);
}
```

The idea being that you inherit from `UserSettings` and provide properties that call the `Get...` and `Set...` methods. For example:

```cs
[SettingsCollection("ProjectFilter_ed6f0249-446a-4ddf-a8e8-b545113ba58f")]
public class ExtensionSettings : UserSettings<ExtensionSettings> {
    public bool LoadProjectDependencies {
        get { return GetBoolean(defaultValue: true); }
        set { SetBoolean(value); }
    }
}
```

And getting an instance is as simple as:

```cs
var settings = await ExtensionSettings.GetAsync();
settings.LoadProjectDependencies = true;
```

Thoughts? If people are happy with the design, then I'll submit a PR.

**Comment by StevenRasmussen** [comment]
I generally like the idea!  I have known about but haven't really used the built-in settings so I'm not sure the correct syntax for getting/setting values but my only thought would be to perhaps just provide generic getter/setter methods:
`GetValue<T>(T defaultValue = default, [CallerMemberName] string? propertyName = null)`
`SetValue<T>(T value, [CallerMemberName] string? propertyName = null))`

If the user tries to pass an unsupported type for `T` then a `NotSupportedException` could be thrown?  Or perhaps we could do some JSON serialization/deserialization under the hood for complex types?  Just throwing some ideas out there.

**Comment by yannduran** [comment]
It sounds good to me.

**Comment by madskristensen** [comment]
How is this different than using the `BaseOptionModel<T>` that's already there?

**Comment by StevenBonePgh** [comment]
I'd agree with Mads here. `BaseOptionModel<T>` is the way to go, and when used with gets you some GUI support for an options page with `BaseOptionPage<T>`.  That said there are fundamental differences between what you propose and that approach.

- In your approach, accessing a property triggers the read/write from settings store and the overriding class is responsible for handling this properly - providing ability for retrieving a default if not exist in your base class methods for get would be good, as well as providing a default complex type serializer.  `BaseOptionModel<T>` is based on a load/save paradigm that uses reflection. So load/save is expensive, runtime access is cheap, and implementation is merely an auto-property with a default - the opposite of each of these is true for your approach.
- The collection name is an attribute in yours, and an overridable property in `BaseOptionModel<T>` that defaults to `typeof(T).FullName`. `OverrideCollectionNameAttribute` can be applied to a property to override the default for a specific property. If submitting this, I'd suggest using the same semantics of a virtual property with the same name and default rather than using an attribute for this purpose.
- In your approach, the name of the setting can be different than the property name, which is not possible in   `BaseOptionModel<T>`. If desired, an attribute to override this could be added to `BaseOptionModel<T>`
- Storage 'type' in your approach is up to the implementer of the property, and this is easy to select the proper storage type by calling the appropriate base class method to load/save. This is where `BaseOptionModel<T>` is weird, as the default storage mechanism ALWAYS uses a `BinaryFormatter` and saves as a Base64 string, though you can use `OverrideDataTypeAttribute` to specify the specific storage type.

A good place to see a sample of `BaseOptionModel<T>` and  `BaseOptionPage<T>` in-use is [Mad's Tweaks extension](https://github.com/madskristensen/Tweakster) - search for `"internal partial class Options"`

**Comment by reduckted** [comment]
> @madskristensen How is this different than using the BaseOptionModel<T> that's already there?

To be honest, I didn't even look at options and didn't realize they are also saved to a `WritableSettingsStore`. I don't need (or want) a GUI for these settings which is why I didn't even consider the options classes. 😄 

The main difference between `BaseOptionModel` and my approach is that I don't have to manually load or save the settings. They are loaded when the property is read, and saved when the property is written.

**Comment by madskristensen** [comment]
`BaseOptionModel<T>` doesn't provide any UI at all. It's just a wrapper around the setting store. It's the `BaseOptionPage<T>` that introduces the UI that can be registered on the package class.

**Comment by reduckted** [comment]
Closing in favor of #112 and maybe some other improvements to `BaseOptionsModel`. 😄
