### ISSUE TITLE
Restore vs-threading analyzers, plus VSTHRD003 warning in FireAndForget

### ISSUE THREAD

**Issue by bluetarpmedia** [VsixCommunity/Community.VisualStudio.Toolkit#24]
The .editorconfig contains this:

```
dotnet_diagnostic.VSTHRD003.severity=silent
dotnet_diagnostic.VSTHRD104.severity=silent
dotnet_diagnostic.VSTHRD111.severity = none
```

I think that should all be removed and any underlying issues in the code that produce these warnings should be fixed, or the warning should only be suppressed around the specific code/method with a justification.

I removed them and did a rebuild and the only vs-threading analyzer warning was VSTHRD003 in the `public static void FireAndForget(this System.Threading.Tasks.Task task)` extension method, so at the very least I think the 104 and 111 analyzers can be re-enabled.

I'm unsure whether the VSTHRD003 warning is a problem in this case. The task has already started before the extension method is called, and it has a different ExecutionContext to the FireAndForget extension method, and that appears to be exactly what VSTHRD003 is warning about.

See: https://github.com/microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD003.md

(Where it talks about foreign tasks from another context I believe it's referring to ExecutionContext -- i.e. the task started on a different stack frame.)

@AArnott Any chance you could comment on this please?

```
public static void FireAndForget(this System.Threading.Tasks.Task task)
{
    ThreadHelper.JoinableTaskFactory.RunAsync(async () =>
    {
        try
        {
            await task.ConfigureAwait(false);  <---- VSTHRD003 here
        }
        catch (Exception ex)
        {
            await ex.LogAsync();
        }
    });
}
```

**Comment by AArnott** [comment]
I totally agree that no threading or vssdk analyzer should be wholesale turned off.

The `FireAndForget` method does represent a violation of VSTHRD003, although strictly speaking in this case it doesn't matter since it can never turn into a deadlock since the JoinableTask created is then dropped without blocking.
But that latter point _is_ a problem, as it's a violation of [this guidance](https://github.com/Microsoft/vs-threading/blob/main/doc/cookbook_vs.md#how-to-write-a-fire-and-forget-method-responsibly).
So IMO this whole method should be removed.

**Comment by madskristensen** [comment]
@AArnott how does the `FireAndForget` method differ from the `FileAndForget` or `Forget` methods already in the VSSDK? The reason for having the `FireAndForget` method in the toolkit is to make the feature available to earlier versions of VS.

**Comment by AArnott** [comment]
`FileAndForget` is not for customers' use. It sends failures to *our* telemetry systems. But it was arguably ill-advised for the same reason as any other forget-style method because it doesn't block shutdown.
`Forget` comes from the vs-threading library and is ok for other apps to use -- but not for VS, since VS hosts the CLR and may tear it down before terminating the process.

**Comment by madskristensen** [comment]
I'm a bit confused. Then what is the right way to start an async method that you don't care awaiting for?

**Comment by bluetarpmedia** [comment]
As I understand it, there are 3 issues that need to be considered with a fire-and-forget method in VS:

1. Catch all exceptions (and log/report to help with maintenance)
2. Ensure tasks are joined before AppDomain shutdown
3. Ensure tasks are joined to keep the application (the extension application logic, not VS itself) in a correct state

Using `ThreadHelper`'s JoinableTaskFactory is a problem with 2, since it won't track the JoinableTask (because it's never added to a collection), and hence nothing will ever ensure that task is joined later unless the client code does it itself. Whereas the `AsyncPackage` JTF does add the task to a collection so at the very least the task will get joined correctly before shutdown.

My understanding is that `ThreadHelper.JoinableTaskFactory.RunAsync` (note the ThreadHelper) should only ever be used if the client code is going to await/join that resulting JoinableTask explicitly (either immediately or assign the JoinableTask to a variable and await/join it later).

So the way to solve 2 for a fire-and-forget method is to use the AsyncPackage JTF. And hence it's better to always prefer the AsyncPackage JTF over ThreadHelper.

But that still leaves point 3. It's one thing for the JoinableTask to get joined as part of shutdown, but what if the fire-and-forget method was in the middle of some big state-changing process? Sure, it'll get cancelled and join cleanly, but whatever application-specific thing it was doing may now be in an undefined state. Only the application programmer can determine its needs in this case, I think.

I can't see a way for a static extension method to do 1 & 2 properly (since it only has access to ThreadHelper) unless AsyncPackage (or its JoinableTaskFactory) is a parameter. Then clients could use it like this:

`task.FireAndForget(myPackage);`

But that still leaves 3. Within the Toolkit itself, point 3 may or may not be a problem depending on the fire-and-forget tasks that it launches and does not await.

The way I've tried to implement the above in my own work is to always use the AsyncPackage JTF and, where necessary for point 3, store the JoinableTask in a variable and then later await/join it at some appropriate time.

**Comment by madskristensen** [comment]
Let's say I have a `IWpfTextviewCreationListener` MEF component that subscribes to the `ITextview.Closed` event. And in that `void` eventhandler method, I wish to kick off an async Task? How would I do that when a package class may not even exist?  Or in case the extension has a package class, would that influence how I call the async Task?

The purpose of the `FireAndForget` method was an attempt to ensure that best practices were followed (or so I thought) when using it. If we don't have a central methodology that does the right thing, then extenders are bound to make mistakes like I was. Is there a _good enough_ way of achieving this for everybody's benefit? One of the key selling points of the Toolkit is to make it harder to violate best practices.

**Comment by AArnott** [comment]
The MEF use case is documented in the cookbook that I linked to. The MEF part basically has to do what the AsyncPackage would have done for them.

**Comment by madskristensen** [comment]
According to this https://github.com/microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD003.md, it appears that this is the right way to call an async Task from a void method:

```c#
void MyMethod()
{
    joinableTaskFactory.Run(async delegate
    {
        System.Threading.Tasks.Task task = SomeOperationAsync();
        await task;
    });
}
```

So it uses the `Run` instead of `RunAsync` method which blocks the thread it was called on until the task is completed, but it isn't using 'ConfigureAwait(false)`. 

To make it safe and simple to start a Task from a void method, could we encapsulate that in an extension method like this:

```c#
public static void Start(this System.Threading.Tasks.Task task)
{
    ThreadHelper.JoinableTaskFactory.Run(async () =>
    {
        try
        {
            await System.Threading.Tasks.Task.Yield();
            await task;
        }
        catch (Exception ex)
        {
            await ex.LogAsync();
        }
    });
}
```

We could overload the method to taka a `JoinableTaskFactory`.

Forgive my ignorance on this subject, but I do think this is a key area the Tookit can really help extenders to follow best practices if we get this right.

**Comment by AArnott** [comment]
> So it uses the Run instead of RunAsync method which blocks the thread it was called on until the task is completed, but it isn't using `ConfigureAwait(false)`.

`ConfigureAwait(false)` is mostly irrelevant and considered harmful within a JTF.Run delegate. See further down in the cookbook for [a discussion on that](https://github.com/Microsoft/vs-threading/blob/main/doc/cookbook_vs.md#should-i-await-a-task-with-configureawaitfalse).

> To make it safe and simple to start a Task from a void method, could we encapsulate that in an extension method like this

No. That would mean blocking on a foreign task and violate VSTHRD003.

And anyway, I took your original goal to *not* block on the async work from your event handler. Using JTF.Run would block, so that's not what you want.

Your questions and examples make me wonder if you read the link to the cookbook that I shared earlier, so here it is again: https://github.com/Microsoft/vs-threading/blob/main/doc/cookbook_vs.md#how-to-write-a-fire-and-forget-method-responsibly
It explains exactly how to *not* await on a Task while not destabilizing the app.

**Comment by AArnott** [comment]
> I do think this is a key area the Tookit can really help extenders to follow best practices if we get this right.

I admire your desire to leverage the toolkit to make hard things easier. But threading is fundamentally complex, and the vs-threading library already makes it about as easy as it gets. The VC team have developed a helper class that IIRC may make the pattern implemented by AsyncPackage reusable for other classes. Perhaps your toolkit could offer something like that.
