### ISSUE TITLE
Assemby and file versioning

### ISSUE THREAD

**Issue by madskristensen** [VsixCommunity/Community.VisualStudio.Toolkit#25]
We need to ensure that an assembly and file version is added to the assembly (probably in an `AssemblyInfo.cs` class) in each nuget package, such that multiple versions can be loaded by VS.

We need it to avoid this <https://github.com/madskristensen/Tweakster/issues/76#issuecomment-826548976>

@CZEMacLeod any idea how to do that best?

**Comment by CZEMacLeod** [comment]
@madskristensen I'm not sure how VS handles loading multiple versions of a DLL for extensions - does it use some sort of AppDomain isolation? Or is it a first loaded wins?
Looking at the (latest) nuget packages - they appear to have sensible information.
The AssemblyInformationalVersion is set to the overall file version and includes the git sha.
The AssemblyVersion and AssemblyFileVersion match and look to match the nuget package version - I'm assuming your AppVeyor build script does this.
Perhaps the AssemblyVersion should not be influenced by the build number, and just be set manually when a breaking change occurs?
There are a couple of little things I would probably do with the build scripts and projects to tidy up, but I'm not sure any of them specifically address this issue.
Is there some way, rather than including the DLL in each VSIX, you could distribute a toolkit extension as a dependency, which would effectively always be the latest version, and so it would have the correct version loaded in memory?
I guess this is one of the issues that goes away with out of process extensions when that arrives...

**Comment by CZEMacLeod** [comment]
Just did a bit more research - does [`ProvideBindingRedirectionAttribute`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.providebindingredirectionattribute) not solve this issue.
I think since you already inject the [`AssemblyInfo.cs`](https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/blob/master/src/AssemblyInfo.cs) file, it should be possible to add
```cs
[assembly: ProvideBindingRedirection(AssemblyName = "Community.VisualStudio.Toolkit",
    NewVersion = "16.0.76.0", OldVersionLowerBound = "1.0.0.0",
    OldVersionUpperBound = "16.0.76.0")]
```
Where `16.0.76.0` would be the AssemblyVersion of the toolkit.

Using `WriteCodeFragment` to dynamically generate the cs file on build would probably make life easier and then the assembly version could be held in a `toolkit.version.props` file that was included from both the toolkit for build and the consumer extension for the redirect.

**Comment by madskristensen** [comment]
I believe VS will load multiple versions in memory if the assemblies are versioned correctly. Perhaps @bertanaygun knows?

**Comment by BertanAygun** [comment]
While loading multiple versions for the same assembly is possible, something will have to let .net loader know where different versions are. Normally this would be the code base attribute. Binding redirects may not be a great option here as it would require no breaking changes between versions, although if that can be done it would be the best option since it would ensure we always load the latest and have a single copy.

Something worth trying could be adding ProvideCodeBase attributes (https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.providecodebaseattribute?view=visualstudiosdk-2019) for the toolkit assemblies to each extension and test what happens in case of multiple extensions targeting different versions and also same version. I believe one of them will overwrite other entries but it shouldn't matter since it will still be the correct version. When that extension is uninstalled pkgdef from the other ones will still keep the entry.

The disadvantage here is that with minor versions we may end up loading many copies of the toolkit assemblies.

**Comment by madskristensen** [comment]
@BertanAygun There is a .targets file in the toolkit package that adds the `ProvideCodeBase` attribute to the consuming extension. However, it doesn't specify the version number. Is that required for VS to load multiple versions?

**Comment by BertanAygun** [comment]
Can you try this instead, the version number should be automatically calculated during pkgdef creation but just specifying AssemblyName may not be enough

[assembly: ProvideCodeBase(CodeBase = @"$PackageFolder$\Community.VisualStudio.Toolkit.dll")]

**Comment by madskristensen** [comment]
That didn't seem to work. Do we need to add a strong name key (.snk) to the assembly?

**Comment by ErikEJ** [comment]
@madskristensen I cannot imagine otherwise

**Comment by madskristensen** [comment]
I added an .snk file

**Comment by BertanAygun** [comment]
I cloned the repo locally and tried building it, and I see that in the pkgdef publicKeyToken is empty string and it causes it to be ignored so resulting devenv.exe.config doesn't have the "dependentAssembly" entry. Did adding an snk file fix the issue?

**Comment by madskristensen** [comment]
Yes, I believe it did. I see this generated in the .pkgdef now:

``` ini
[$RootKey$\RuntimeConfiguration\dependentAssembly\codeBase\{5BBB5194-A871-AB93-FE1E-E84EEFB4277E}]
"name"="Community.VisualStudio.Toolkit"
"publicKeyToken"="79441d341a79572c"
"culture"="neutral"
"version"="16.0.75.40"
"codeBase"="$PackageFolder$\Community.VisualStudio.Toolkit.DLL"
```

**Comment by BertanAygun** [comment]
Once you F5 and deploy, you should also check:
"%LOCALAPPDATA%\Microsoft\VisualStudio\16.0_<id>Exp\devenv.exe.config" to see if it has the dependentAssembly entry for toolkit dll, with publicKeyToken set to a non-empty string the entry should be in the config file now.

I did open a product bug for the potential mismatch between pkgdef reader and generated pkgdef from attribute.

**Comment by madskristensen** [comment]
This is the entry generated:

```xml
<dependentAssembly>
    <assemblyIdentity name="Community.VisualStudio.Toolkit" publicKeyToken="79441d341a79572c" culture="neutral"/>
    <codeBase version="16.0.75.40" href="[long path]\Community.VisualStudio.Toolkit.DLL"/>
</dependentAssembly>
```

**Comment by yannduran** [comment]
Since we're talking about version numbers, I feel very strongly that we should be using semantic versioning. The build number shouldn't be part of the Nuget package number IMO.

**Comment by reduckted** [comment]
Semantic versioning will be tricky if the major version of this package stays aligned with the version of Visual Studio that it targets (i.e v16.x of this package is for Visual Studio 16+).

I do like semantic versioning though!

**Comment by yannduran** [comment]
Yeah I almost mentioned that, but I don't see a way out of it now. Although I understand Mads's intention, it would have been better to have **not** had it aligned with the version of VS for that exact reason.

**Comment by yannduran** [comment]
So does the `ProvideCodeBase` attribute need to be added to consuming extensions, or only in the Nuget package?

**Comment by yannduran** [comment]
When I inspect the `VSSDK.TestExtension.pkgdef` file in the VSIX produced from compiling the test extension in the latest version of the toolkit I see:

>[$RootKey$\RuntimeConfiguration\dependentAssembly\codeBase\{1B111C55-EF92-ACBD-CFED-591501EE2FD6}]
"name"="Community.VisualStudio.Toolkit"
"publicKeyToken"="79441d341a79572c"
"culture"="neutral"
"version"="**16.0.0.0**"
"codeBase"="$PackageFolder$\Community.VisualStudio.Toolkit.DLL"

The version number is 16.0.0.0, not the actual version of the toolkit. This isn't right, surely?

**Comment by madskristensen** [comment]
@yannduran `ProvideCodeBase` is set by the NuGet package only. It would be nice have the CI stamp the right on it too, but it doesn't right now

**Comment by yannduran** [comment]
Interestingly, when I looked in the pkgdef file for Start Page+ it has the correct version number:

>[$RootKey$\RuntimeConfiguration\dependentAssembly\codeBase\{5BBB5194-A871-AB93-FE1E-E84EEFB4277E}]
"name"="Community.VisualStudio.Toolkit"
"publicKeyToken"="79441d341a79572c"
"culture"="neutral"
"version"="16.0.75.40"
"codeBase"="$PackageFolder$\Community.VisualStudio.Toolkit.DLL"
