### ISSUE TITLE
 Figure out how to remove projects and solution folders without the DTE

### ISSUE THREAD

**Issue by madskristensen** [VsixCommunity/Community.VisualStudio.Toolkit#72]
This is used in the `SolutionItem` class and I have no idea how to do it without the DTE

**Comment by bluetarpmedia** [comment]
Have you tried [IVsSolution.CloseSolutionElement](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivssolution.closesolutionelement?view=visualstudiosdk-2019)?

I think if you pass 0 to `grfCloseOpts` it might remove the project from the solution. Because this is what you need to pass to unload a project, and the [docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.__vsslncloseoptions?view=visualstudiosdk-2019) say:
```
SLNCLOSEOPT_UnloadProject | 65536 | If not set, the project is removed from the solution.
```

**Comment by madskristensen** [comment]
Wonderful, I'll try that!! Thanks
