### ISSUE TITLE
Predefined CommandID values for known commands

### ISSUE THREAD

**Issue by reduckted** [VsixCommunity/Community.VisualStudio.Toolkit#93]
The new `Commands` class that lets you execute a command by name and the overloads for `VSConstants.VSStd97CmdID` and so on are fantastic, but knowing which enum the command you want to execute is defined in makes it a bit painful to use. 

I think a `KnownCommands` class that defines the `CommandID` objects for all commands that Visual Studio defines would be great. I've created a proof-of-concept here: https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/compare/master...reduckted:feature/known-commands

The good thing is that the `CommandID`s for all 800+ commands that Visual Studio provides can be generated quite easily (see the PowerShell script).

Here's what you see in intellisense:
![image](https://user-images.githubusercontent.com/10321525/124351190-3c22e380-dc3c-11eb-9de4-8dcc05ca21d8.png)

There's still a few things to improve, but I thought I'd get some opinions before I go any further.

**Comment by madskristensen** [comment]
I absolutely love that!!! The extension method on `CommandID` let's you execute, so you can make it even easier to read by doing:

`await KnownCommands.Build_BatchBuild.ExecuteAsync();`

I was wondering if we should change the signature of the properties, so they don't allocate individual `CommandID` instances for all 800+ commands, but instead create them when needed. 

So instead of this:

```csharp
public static CommandID Build_BatchBuild { get; } = new CommandID(VSConstants.CMDSETID.StandardCommandSet97_guid, 891);
```

should we do this?

```csharp
public static CommandID Build_BatchBuild => new CommandID(VSConstants.CMDSETID.StandardCommandSet97_guid, 891);
```

Also, knowing the exact origin of the command might be of interest, so I'm wondering if we should add that to the `<summary>` instead of keeping it in a separate comment. Something like this:

```csharp
 /// <summary>Build.BatchBuild (VSStd97CmdID.BatchBuildDlg)</summary>
public static CommandID Build_BatchBuild => new CommandID(VSConstants.CMDSETID.StandardCommandSet97_guid, 891);
```

**Comment by reduckted** [comment]
Both very good suggestions. I'll make those changes. 👍
